unify logging content style
alibaba/sentinel-golang pull request #293
Opened 2020-10-15 12:45 UTC by sanxun0325

### Describe what this PR does / why we need it
unify logging content style

### Does this pull request fix one issue?
Fixes:https://github.com/alibaba/sentinel-golang/issues/280

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2020-10-15 13:56 UTC, liqiangz commented on core/circuitbreaker/circuit_breaker.go
> +		logging.Error(errors.New("bucket data type error"), "Bucket data type error in  slowRequestLeapArray.currentCounter()")
There are extra spaces between "in" and "slowRequestLeapArray".

2020-10-15 14:10 UTC, liqiangz commented on core/stat/base/sliding_window_metric.go
> +			logging.Error(errors.New("nil BucketWrap"), "Current bucket Value is nil in SlidingWindowMetric.metricItemFromBuckets()")
value should be lowercase？

2020-10-15 14:11 UTC, liqiangz commented on core/stat/base/sliding_window_metric.go
> +		logging.Error(errors.New("nil BucketWrap"), "Current bucket Value is nil in SlidingWindowMetric.metricItemFromBucket()")
Here is the same as above

2020-10-15 14:23 UTC, liqiangz commented on ext/datasource/file/refreshable_file.go
> +							logging.Error(errors.New("Retry failed "), "Fail to retry watch", "sourceFilePath", s.sourceFilePath)
Here should be unified into lower case, and there are extra spaces.

2020-10-21 14:29 UTC, louyuting commented on core/circuitbreaker/circuit_breaker.go
> +		logging.Error(errors.New("bucket data type error"), "Bucket data type error in slowRequestLeapArray.currentCounter()")
You might need to indicate "type assert failed, expect *slowRequestCounter"

2020-10-21 14:29 UTC, louyuting commented on core/circuitbreaker/circuit_breaker.go
> +			logging.Error(errors.New("bucket data type error"), "Bucket data type error in slowRequestLeapArray.allCounter()")
Same with uppon

2020-10-21 14:29 UTC, louyuting commented on core/circuitbreaker/circuit_breaker.go
> +		logging.Error(errors.New("bucket data type error"), "Bucket data type error in errorCounterLeapArray.currentCounter()")
Same with uppon

2020-10-22 06:07 UTC, louyuting requested changes

2020-10-23 15:18 UTC, louyuting submitted a review, later dismissed
Nice work

2020-10-23 15:29 UTC, louyuting approved these changes

2020-10-23 15:34 UTC, merged