### feature：
alibaba/sentinel-golang pull request #583
Opened 2024-10-04 14:52 UTC by 578223592

### Describe what this PR does / why we need it
bug-fix

### Does this pull request fix one issue?
Fixes 
- https://github.com/alibaba/sentinel-golang/issues/563
- typo

### Describe how you did it
add more fields for compare

### Describe how to verify it
add one  more test case

### Special notes for reviews

2024-10-04 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/sentinel-golang?pullRequest=583) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/sentinel-golang?pullRequest=583) before we can accept your contribution.<br/><hr/>**caicai** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/sentinel-golang?pullRequest=583) it.</sub>

2024-10-08 02:16 UTC, binbin0325 requested changes

2024-10-08 02:16 UTC, binbin0325 commented on core/circuitbreaker/rule.go
> +		r.MaxAllowedRtMs == newRule.MaxAllowedRtMs && r.Threshold == newRule.Threshold && r.ProbeNum == newRule.ProbeNum
MaxAllowedRtMs & Threshold, should not be involved in comparison

2024-10-09 12:10 UTC, 578223592 commented on core/circuitbreaker/rule.go
> +		r.MaxAllowedRtMs == newRule.MaxAllowedRtMs && r.Threshold == newRule.Threshold && r.ProbeNum == newRule.ProbeNum
isEqualsToBase应该只判断所有类型的rule都生效的配置

2024-10-10 02:00 UTC, binbin0325 approved these changes
LGTM

2024-10-10 02:06 UTC, merged